name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build Windows
        if: runner.os == 'Windows'
        run: go build -ldflags="-s -w" -v -o vent.exe .

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: vent.exe
          args: "-9"

      - name: Release Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows'
        with:
          files: |
            client.exe
            host.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}